version: '3.8'
services:
  app:
    build: ./docker
    container_name: nginxPhpLaravelProject-app
    volumes:
      - ./app:/var/www/app

  nginx:
    image: nginx:latest
    container_name: nginxPhpLaravelProject-nginx
    ports:
      - 8080:80 
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  db:
    image: mysql:latest
    container_name: nginxPhpLaravelProject-db
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"